name: 'Build LaTex Document'
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install CJK fonts 
      run: sudo apt update -qq && sudo apt-get install -y fonts-noto-cjk-extra && sudo fc-cache -fv
    - uses: actions/cache@v2
      name: Tectonic Cache
      with:
        path: ~/.cache/Tectonic
        key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
        restore-keys: |
           ${{ runner.os }}-tectonic-
    - uses: wtfjoke/setup-tectonic@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Compile TeX to PDF
      run: tectonic main.tex
